services:
  backend:
    build:
      target: production
    restart: always
    volumes:
      - backend_logs:/app/logs
    # Remove source code volume mounts for production

  frontend:
    build:
      target: production
    restart: always
    # Remove source code volume mounts for production

  nginx:
    image: nginx:alpine
    container_name: appointments-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - appointments-network
    depends_on:
      - backend
      - frontend
