services:
  backend:
    build:
      target: dev
    volumes:
      - ./appointments-backend:/app:rw
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      target: dev
    volumes:
      - ./appointments-frontend:/app:rw
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
